### ISSUE TITLE
Use on non-Django models, such as Mongoengine models

### ISSUE THREAD

**Issue by codekiln** [Codoc-os/django-opensearch-dsl#42]
In a Django project I work on, we use Mongoengine inside of Django in addition to Django models. Mongoengine is not a drop-in replacement for Django models, though Mongoengine models are influenced by Django. 

Would it be as simple as subclassing `Document` and then ignoring the django-specific type hints, with light updates to call to the external datastore? What methods are called on the model when specifying the indexing, and how could that be adapted to external datastores such as mongoengine?

**Comment by qcoumes** [comment]
This is off the top of my head, but the only calls on the models are done in `Document.get_queryset()` / `Document.get_indexing_queryset()`. This is mainly `model.objects.all()` and `model.objects.count()`, but `filter()` and `exclude()` and `__getitem__()` are also called if the respective `filter_`, `exclude` and `count` arguments are provided.

Everything else is done in `DODField.get_value_from_instance()` through attribute/item fetching which I suppose should work with Mongoengine.

The main problem may be handling many-to-many and many-to-one relations since we're using Django model managers to fetch the objects in `DODField.get_value_from_instance()`, and redefining this method means redefining all fields with your custom `DODField`.

Last but not least, if you want automatic mapping, you will need to redefine `Document.to_field` to match your Mongoengine fields with OpenSearch fields.
